Repository Hanghae-MealFit/MealFit-BackEnd, pull requests merged in 2022-08, with the labels that each got.

#8 #4 회원가입 구현
  build.gradle
  src/main/java/com/mealfit/MealfitApplication.java
  src/main/java/com/mealfit/common/crypt/AES128.java
  src/main/java/com/mealfit/common/crypt/CryptoConverter.java
  src/main/java/com/mealfit/common/error/ErrorCode.java
  src/main/java/com/mealfit/common/error/ErrorResponse.java
  src/main/java/com/mealfit/common/healthCheck/HealthCheckController.java
  src/main/java/com/mealfit/common/logging/AOPLogging.java
  src/main/java/com/mealfit/config/security/WebSecurityConfig.java
  src/main/java/com/mealfit/email/EmailUtil.java
  src/main/java/com/mealfit/email/FindPasswordEmail.java
  src/main/java/com/mealfit/email/SendingEmailStrategy.java
  src/main/java/com/mealfit/email/SignUpEmail.java
  src/main/java/com/mealfit/user/controller/UserController.java
  src/main/java/com/mealfit/user/controller/UserExceptionHandler.java
  src/main/java/com/mealfit/user/domain/EmailCertification.java
  src/main/java/com/mealfit/user/domain/User.java
  src/main/java/com/mealfit/user/domain/UserStatus.java
  src/main/java/com/mealfit/user/dto/SignUpRequestDto.java
  src/main/java/com/mealfit/user/repository/EmailCertificationRepository.java
  src/main/java/com/mealfit/user/repository/UserRepository.java
  src/main/java/com/mealfit/user/service/UserService.java
  src/main/resources/application-DEV.yaml
  src/main/resources/application.yaml
Labels: enhancement

#11 [#9] 아이디, 비밀번호 찾기 구현
  build.gradle
  src/main/java/com/mealfit/common/email/EmailUtil.java
  src/main/java/com/mealfit/common/email/FindPasswordEmail.java
  src/main/java/com/mealfit/common/email/SendingEmailStrategy.java
  src/main/java/com/mealfit/common/email/SignUpEmail.java
  src/main/java/com/mealfit/common/error/ErrorCode.java
  src/main/java/com/mealfit/common/error/ErrorResponse.java
  src/main/java/com/mealfit/user/controller/UserController.java
  src/main/java/com/mealfit/user/controller/UserExceptionHandler.java
  src/main/java/com/mealfit/user/dto/SignUpRequestDto.java
  src/main/java/com/mealfit/user/service/UserService.java
Labels: documentation

#17 #16 회원가입 조건 디버깅
  src/main/java/com/mealfit/user/controller/UserController.java
Labels: bug

#19 Meal fit back end 7
  src/main/java/com/mealfit/diet/controller/DietController.java
  src/main/java/com/mealfit/diet/domain/Diet.java
  src/main/java/com/mealfit/diet/domain/UserFood.java
  src/main/java/com/mealfit/diet/dto/DietCUDResponseDto.java
  src/main/java/com/mealfit/diet/dto/DietListResponseDto.java
  src/main/java/com/mealfit/diet/dto/DietRequestDto.java
  src/main/java/com/mealfit/diet/dto/DietResponseDto.java
  src/main/java/com/mealfit/diet/dto/FoodListDto.java
  src/main/java/com/mealfit/diet/dto/PostRequestDto.java
  src/main/java/com/mealfit/diet/dto/UserGoalDto.java
  src/main/java/com/mealfit/diet/repository/DietRepository.java
  src/main/java/com/mealfit/diet/service/DietService.java
  src/main/java/com/mealfit/food/controller/FoodController.java
  src/main/java/com/mealfit/food/domain/Food.java
  src/main/java/com/mealfit/food/dto/FoodDto.java
  src/main/java/com/mealfit/food/dto/FoodRequestDto.java
  src/main/java/com/mealfit/food/dto/FoodResponseDto.java
  src/main/java/com/mealfit/food/repository/FoodRepository.java
  src/main/java/com/mealfit/food/service/FoodService.java
Labels: enhancement

#21 #20 1차 수정 완료
  src/main/java/com/mealfit/diet/controller/DietController.java
  src/main/java/com/mealfit/diet/controller/DietExceptionHandler.java
  src/main/java/com/mealfit/diet/domain/Diet.java
  src/main/java/com/mealfit/diet/domain/UserFood.java
  src/main/java/com/mealfit/diet/dto/DietResponseDto.java
  src/main/java/com/mealfit/food/controller/FoodController.java
  src/main/java/com/mealfit/food/controller/FoodExceptionHandler.java
  src/main/java/com/mealfit/food/domain/Food.java
  src/main/java/com/mealfit/food/dto/FoodResponseDto.java
  src/main/java/com/mealfit/food/service/FoodService.java
  src/main/java/com/mealfit/loginJwtSocial/auth/UserDetailsImpl.java
  src/main/java/com/mealfit/loginJwtSocial/jwtFilter/FormLoginFilter.java
  src/main/java/com/mealfit/user/domain/User.java
Labels: enhancement

#26 #25 로그인 리팩토링
  build.gradle
  src/main/java/com/mealfit/common/error/CommonResponse.java
  src/main/java/com/mealfit/common/error/ErrorCode.java
  src/main/java/com/mealfit/common/error/ErrorResponseUtils.java
  src/main/java/com/mealfit/config/security/OAuth/CustomOAuth2UserService.java
  src/main/java/com/mealfit/config/security/OAuth/OAuth2Attribute.java
  src/main/java/com/mealfit/config/security/WebSecurityConfig.java
  src/main/java/com/mealfit/config/security/details/UserDetailsImpl.java
  src/main/java/com/mealfit/config/security/details/UserDetailsServiceImpl.java
  src/main/java/com/mealfit/config/security/dto/LoginRequestDto.java
  src/main/java/com/mealfit/config/security/dto/LoginResponseDto.java
  src/main/java/com/mealfit/config/security/exception/DeniedJwtException.java
  src/main/java/com/mealfit/config/security/filter/FormLoginFilter.java
  src/main/java/com/mealfit/config/security/filter/JwtAuthorizationFilter.java
  src/main/java/com/mealfit/config/security/handler/OAuth2SuccessHandler.java
  src/main/java/com/mealfit/config/security/jwt/JwtUtils.java
  src/main/java/com/mealfit/config/security/jwt/VerifyResult.java
  src/main/java/com/mealfit/config/security/provider/FormLoginProvider.java
  src/main/java/com/mealfit/config/security/provider/JwtAuthorizationProvider.java
  src/main/java/com/mealfit/config/security/token/JwtAuthenticationToken.java
  src/main/java/com/mealfit/diet/controller/DietController.java
  src/main/java/com/mealfit/diet/controller/DietExceptionHandler.java
  src/main/java/com/mealfit/food/controller/FoodController.java
  src/main/java/com/mealfit/food/controller/FoodExceptionHandler.java
  src/main/java/com/mealfit/loginJwtSocial/dto/LoginIdCheckDto.java
  src/main/java/com/mealfit/loginJwtSocial/dto/MemberDto.java
  src/main/java/com/mealfit/loginJwtSocial/jwtFilter/JwtAuthorizationFilter.java
  src/main/java/com/mealfit/loginJwtSocial/social/AccountController.java
  src/main/java/com/mealfit/loginJwtSocial/social/KakaoProfile.java
  src/main/java/com/mealfit/loginJwtSocial/social/KakaoService.java
  src/main/java/com/mealfit/loginJwtSocial/social/KakaoUser.java
  src/main/java/com/mealfit/loginJwtSocial/social/OAuthToken.java
  src/main/java/com/mealfit/loginJwtSocial/social/RestTemplateConfig.java
  src/main/java/com/mealfit/user/controller/UserExceptionHandler.java
  src/main/java/com/mealfit/user/domain/OAuthType.java
  src/main/java/com/mealfit/user/domain/User.java
  src/main/java/com/mealfit/user/domain/UserStatus.java
  src/main/java/com/mealfit/user/service/UserService.java
Labels: enhancement

#35 #31 로그인 디버깅
  build.gradle
  src/main/java/com/mealfit/common/s3/S3Service.java
  src/main/java/com/mealfit/config/security/OAuth/CustomOAuth2UserService.java
  src/main/java/com/mealfit/config/security/OAuth/OAuth2UserInfo/GoogleUserInfo.java
  src/main/java/com/mealfit/config/security/OAuth/OAuth2UserInfo/KakaoUserInfo.java
  src/main/java/com/mealfit/config/security/OAuth/OAuth2UserInfo/NaverUserInfo.java
  src/main/java/com/mealfit/config/security/OAuth/OAuth2UserInfo/OAuth2UserInfo.java
  src/main/java/com/mealfit/config/security/OAuth/OAuth2UserInfoFactory.java
  src/main/java/com/mealfit/config/security/OAuth/UserPrincipal.java
  src/main/java/com/mealfit/config/security/OAuth/handler/OAuth2SuccessHandler.java
  src/main/java/com/mealfit/config/security/WebSecurityConfig.java
  src/main/java/com/mealfit/config/security/details/UserDetailsImpl.java
  src/main/java/com/mealfit/config/security/details/UserDetailsServiceImpl.java
  src/main/java/com/mealfit/config/security/filter/JwtAuthorizationFilter.java
  src/main/java/com/mealfit/config/security/jwt/VerifyResult.java
  src/main/java/com/mealfit/config/security/provider/JwtAuthorizationProvider.java
  src/main/java/com/mealfit/config/security/token/JwtAuthenticationToken.java
  src/main/java/com/mealfit/post/controller/PostController.java
  src/main/java/com/mealfit/post/service/PostReadService.java
  src/main/java/com/mealfit/user/controller/UserController.java
  src/main/java/com/mealfit/user/domain/ProviderType.java
  src/main/java/com/mealfit/user/domain/User.java
  src/main/java/com/mealfit/user/domain/UserStatus.java
  src/main/java/com/mealfit/user/dto/SignUpRequestDto.java
  src/main/java/com/mealfit/user/service/UserService.java
  src/main/resources/application.yaml
Labels: bug
